name: "Code Check"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install ruff
      run: |
        python -m pip install ruff

    - name: Run ruff check and format
      run: |
        ruff check
        ruff format